KUR_BA100: &KUR
  network: ./data/networks/BA_100.csv
  N: 1000
  dt: 0.01
  root_type: node
  variables:
    independent:
      x:
        type: node
        initialize: np.random.uniform(-np.pi, np.pi, (1, V))
        update: np.mod(x + dx * dt + np.pi, 2 * np.pi) - np.pi
      omega:
        type: node
        initialize: np.random.normal(1, 0.8, (1, V))
    dependent:
      dx:
        type: node
        GD_expr: omega + 1.0*aggr(sin(sour(x, G, A)-targ(x, G, A)), G, A)
  plot: [sin(x)]

KUR_clear:
  network: ./data/networks/LFR_clear.csv
  <<: *KUR

KUR_fuzzy:
  network: ./data/networks/LFR_fuzzy.csv
  <<: *KUR


MM_BA100: &MM
  network: ./data/networks/BA_100.csv
  N: 400
  dt: 0.01
  root_type: node
  variables:
    independent:
      x:
        type: node
        initialize: np.random.uniform(0.1, 5.0, (1, V))
        update: x + dx * dt
    dependent:
      dx:
        type: node
        GD_expr: -x + aggr(sour(regular(x, 2), G, A), G, A)
  plot: [x]

MM_clear:
  network: ./data/networks/LFR_clear.csv
  <<: *MM

MM_fuzzy:
  network: ./data/networks/LFR_fuzzy.csv
  <<: *MM
