hetero_edge_kuramoto:
  network: 
    use: ./data/networks/BA_100.csv
  N: 1000
  dt: 0.01
  root_type: node
  variables:
    independent:
      x:
        type: node
        initialize: np.random.uniform(-np.pi, np.pi, (1, V))
        update: np.mod(x + dx * dt + np.pi, 2 * np.pi) - np.pi
      omega:
        type: node
        initialize: np.random.normal(1.0, 0.1, (1, V))
      w:
        type: edge
        initialize: np.random.uniform(0.5, 1.0, (1, E))
    dependent:
      dx:
        type: node
        GD_expr: omega + 1.0*aggr(w * sin(sour(x, G, A)-targ(x, G, A)), G, A)
  plot: [sin(x)]

homo_edge_kuramoto:
  network:
    use: ./data/networks/BA_100.csv
  N: 1000
  dt: 0.01
  root_type: node
  variables:
    independent:
      x:
        type: node
        initialize: np.random.uniform(-np.pi, np.pi, (1, V))
        update: np.mod(x + dx * dt + np.pi, 2 * np.pi) - np.pi
      omega:
        type: node
        initialize: np.random.normal(1.0, 0.1, (1, V))
    dependent:
      dx:
        type: node
        GD_expr: omega + 1.0*aggr(sin(sour(x, G, A)-targ(x, G, A)), G, A)
  plot: [sin(x)]